### ISSUE TITLE
Questions Regarding Results Using NASTRA

### ISSUE THREAD

**Issue by HLHsieh** [renzilin/NASTRA#4]
Hi Zilin,

Thank you for your help so far. I’ve completed part of my research and am now working on the manuscript. I have a few questions related to some of the settings and results, and I believe your input will help me explain the results more clearly.

1. Regarding threshold.cfg, I’d like to confirm my understanding:

```
locus,cov_0,cov_10,cov_15,cov_20,cov_25,cov_30,cov_50
C9ORF72,0.31,0.3,0.35,0.36,0.375,0.345,0.39
```
Do the numbers following cov_ refer to the --sncutoff (or SN) setting in the parameters, or are they related to sequencing depth? Additionally, do values like 0.31, 0.3, etc., correspond to the SN ratio?
You also mentioned previously that I could set these thresholds based on my specific experiments or data. Could you provide guidance on how to obtain this information?

2. Last time, you suggested modifying the code as follows. Could you explain the purpose of this modification?
```
if len(raw_reads) < 0:
            result = [[barcode, locus, '<None>', '<None>', len(raw_reads), '<LowCov>']]
            clipped_dat = pd.DataFrame(result, columns=['barcode', 'locus', 'seq', 'genotype', 'sn', 'sn_ratio'])
```

3. In my study, I observed that as the error rate increases, accuracy slightly decreases. I assume this is due to the structure-aware algorithm, which is designed to identify exact TR motif matches, making it sensitive to sequencing errors. Consequently, I concluded that “NASTRA demonstrated superior performance for STR lengths under 1 kb, assuming a reasonable error rate. However, the final allele calls may lack complete units, and errors in read clustering could contribute to reduced accuracy, particularly at higher error rates.” Please let me know if there are any inaccuracies in my explanation. Any additional insights into this phenomenon would also be appreciated.

4. Additionally, I found an update on handling incomplete units, and I noticed that your previous bioRxiv manuscript states, “While NASTRA can detect incomplete repeat units in the output allele, it does not integrate this digital information into its allele calls.” Could you clarify what an incomplete unit is and its potential impact on further analysis?

5. According to repeat_structure.pat, I assume NASTRA can be applied to complex tandem repeats, such as GCCA and AAATT, and report both repeat structures information. Is that correct?

Thank you very much for your time and guidance. I believe your insights will be invaluable in helping me clarify these aspects and enhance the accuracy of my manuscript.

Best regards,
Hsin

**Comment by renzilin** [comment]
> Hi Zilin,
> 
> Thank you for your help so far. I’ve completed part of my research and am now working on the manuscript. I have a few questions related to some of the settings and results, and I believe your input will help me explain the results more clearly.
> 
> 1. Regarding threshold.cfg, I’d like to confirm my understanding:
> 
> ```
> locus,cov_0,cov_10,cov_15,cov_20,cov_25,cov_30,cov_50
> C9ORF72,0.31,0.3,0.35,0.36,0.375,0.345,0.39
> ```
> 
> Do the numbers following cov_ refer to the --sncutoff (or SN) setting in the parameters, or are they related to sequencing depth? Additionally, do values like 0.31, 0.3, etc., correspond to the SN ratio? You also mentioned previously that I could set these thresholds based on my specific experiments or data. Could you provide guidance on how to obtain this information?
> 
> 2. Last time, you suggested modifying the code as follows. Could you explain the purpose of this modification?
> 
> ```
> if len(raw_reads) < 0:
>             result = [[barcode, locus, '<None>', '<None>', len(raw_reads), '<LowCov>']]
>             clipped_dat = pd.DataFrame(result, columns=['barcode', 'locus', 'seq', 'genotype', 'sn', 'sn_ratio'])
> ```
> 
> 3. In my study, I observed that as the error rate increases, accuracy slightly decreases. I assume this is due to the structure-aware algorithm, which is designed to identify exact TR motif matches, making it sensitive to sequencing errors. Consequently, I concluded that “NASTRA demonstrated superior performance for STR lengths under 1 kb, assuming a reasonable error rate. However, the final allele calls may lack complete units, and errors in read clustering could contribute to reduced accuracy, particularly at higher error rates.” Please let me know if there are any inaccuracies in my explanation. Any additional insights into this phenomenon would also be appreciated.
> 4. Additionally, I found an update on handling incomplete units, and I noticed that your previous bioRxiv manuscript states, “While NASTRA can detect incomplete repeat units in the output allele, it does not integrate this digital information into its allele calls.” Could you clarify what an incomplete unit is and its potential impact on further analysis?
> 5. According to repeat_structure.pat, I assume NASTRA can be applied to complex tandem repeats, such as GCCA and AAATT, and report both repeat structures information. Is that correct?
> 
> Thank you very much for your time and guidance. I believe your insights will be invaluable in helping me clarify these aspects and enhance the accuracy of my manuscript.
> 
> Best regards, Hsin

Sorry for the late reply. 

```
1. cov_{SN} is --sncutoff
2. len(raw_reads) means the number of reads spanning the target region
3. I think your conclusion is correct. We made an optimization for the forensic STR loci. And for expansions, it might be not suitable
4. In cell line authentication and human identification, the incomplete unit also contributes to the final genotype, which therefore is important for identity testing. This is solved in a new version in Bib.
5. Yes, we could do this if the repeat structure is already known.
```
